name: Daily Email Automation

on:
  schedule:
    - cron: '0 3 * * *'  # Jam 03:00 UTC = jam 10:00 WIB
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python tesviewanomali.py
